---
- hosts: all
  tasks:
     - name: Deploy NTP SVC
       yum:
         name: ntp
         state: present
       when:
         ansible_os_family == "RedHat"

     - name: Restart NTP SVC
       service:
         name: ntpd
         state: started
         enabled: yes
       when:
         ansible_os_family == "RedHat"

     - name: Deploy NTP files
       copy:
         src: files/ntp.conf
         dest: /etc/ntp.conf 
         backup: yes
       notify: 
         - Restart NTP SVC
       register: log_out
       when:
         ansible_os_family == "RedHat"

  handlers:
     - name: Restart NTP SVC
       service:
         name: ntpd
         state: restarted
       when:
         ansible_os_family == "RedHat"
