---
- hosts: all
  tasks:
     - name: Deploy NTP SVC
       yum:
         name: ntp
         state: present
       when:
         ansible_os_family == "RedHat"

     - name: Restart NTP SVC
       service:
         name: ntpd
         state: restarted
         enabled: yes
       when:
         ansible_os_family == "RedHat"

 
